# Generated by Django 5.2.4 on 2025-08-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("status", models.CharField(default="Applied", max_length=50)),
                ("date_applied", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
