# Generated by Django 5.2.5 on 2025-08-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="interview_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
