# Generated by Django 5.2.5 on 2025-08-28 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_jobapplication_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="rounds",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="salary_offered",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField()),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("Phone", "Phone"),
                            ("Online", "Online"),
                            ("Onsite", "Onsite"),
                            ("Other", "Other"),
                        ],
                        default="Online",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="tracker.jobapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=300)),
                ("topic", models.CharField(blank=True, max_length=100)),
                ("was_asked", models.BooleanField(default=True)),
                ("my_answer", models.TextField(blank=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="tracker.interview",
                    ),
                ),
            ],
        ),
    ]
